### ISSUE TITLE
Error in fmlogit

### ISSUE THREAD

**Issue by yyatsyn** [f1kidd/fmlogit#1]
Trying to run even the help-file example, I get the following error:

Error in parse(text = x, keep.source = FALSE) : 
  <text>:2:0: unexpected end of input
1: ~
   ^

**Comment by hong-xia** [comment]
Had the same issue above, I think it's because it assumes there will be factor/categorical variable there, if the variables are all numerical, then the above error is triggered (fmlogit_main.R - line 85)

**Comment by bellowswang** [comment]
same here

**Comment by johnwoodill** [comment]
I fixed this and have uploaded a [pull request](https://github.com/f1kidd/fmlogit/pull/2). See [changes here](https://github.com/f1kidd/fmlogit/pull/2/files)

**Comment by f1kidd** [comment]
Hello guys, 

John's fix works perfectly. I've updated the master file myself, so use either John's pull file or just the main function in master. 

Thanks a lot John!!

James
