### ISSUE TITLE
Error in marginals.R

### ISSUE THREAD

**Issue by johnwoodill** [f1kidd/fmlogit#3]
Can't get marginal effects because of an error:

```
Error in ans[!test & ok] <- rep(no, length.out = length(ans))[!test &  : 
  replacement has length zero
In addition: Warning message:
In rep(no, length.out = length(ans)) :
  'x' is NULL so the result will be NULL
```
The error is related to [line 174](https://github.com/f1kidd/fmlogit/blob/7ef7924c47c4e3fe52af1ca10d078872a6fcb9a7/R/marginals.R#L174) in `marginals.R`
`  outlist$R = ifelse(se==T,R,NULL)`

A simple fix is to change `NULL` to `NA`
`  outlist$R = ifelse(se==T,R,NA)`

See new pull request for fix.

**Comment by f1kidd** [comment]
Great catch. I've uploaded my own version, which changes NA to 0. Should do the same trick. Both file works fine.

**Comment by weizhe11** [comment]
Thanks!!
