### ISSUE TITLE
Is there any examples on how to use the package?

### ISSUE THREAD

**Issue by colospring** [f1kidd/fmlogit#6]
Hi there, I was looking for an R package that can deal with fractional multinomial logistic regression and found this package. It seems just like what I need! I was wondering whether there are some examples to show how to use this package? Many thanks!

**Comment by f1kidd** [comment]
After installing the package, try the following code, which performs FMNL on the Danish governmental spending dataset:

#### code chunk ####
data = spending
X = data[,2:5]
y = data[,6:11]
results1 = fmlogit(y,X)

Have fun!
