### ISSUE TITLE
Can you add a license?

### ISSUE THREAD

**Issue by NicholasAPotter-USDA** [f1kidd/fmlogit#7]
@f1kidd thanks for writing an R version of fmlogit. Would you mind adding a LICENSE file? I was hoping to write a PR to allow for weights, but it's hard to know what I can do without something like an [MIT license](https://choosealicense.com/licenses/mit/).

Here is some discussion on licensing from the [R Packages book](https://r-pkgs.org/license.html).

**Comment by f1kidd** [comment]
Set to MIT license on the Description page. Thanks for contributing, Nick!
